# Lista 07 - Comparando Classificadores

# Exercício 01:

Analise o desempenho do kNN e de uma Regressão Logística Regularizada para **pelo menos um** dos conjuntos de dados abaixo:

* [Avaliação de carros](http://archive.ics.uci.edu/ml/datasets/Car+Evaluation)
* [Avaliação de vinhos](http://archive.ics.uci.edu/ml/datasets/Wine+Quality)
* [Resultados de partidas do jogo Dota](http://archive.ics.uci.edu/ml/datasets/Dota2+Games+Results) (desafiador!)

Para a questão, faça as seguintes tarefas:

* Realize treino, validação e teste
* Compare as métricas no teste
* Reporte a precisão, revocação, F1 e a matriz de confusão

Como já estamos no fim da matéria, você pode agora fazer uso da biblioteca scikit-learn. Afinal, no dia a dia, não implementamos tudo do zero. Abaixo temos os imports que vocês precisam. Leiam a API da biblioteca para saber como fazer uso da mesma.

In [1]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support

from sklearn.neighbors import KNeighborsClassifier

# Um fator importante é que o SKLearn não cria conjuntos de validação para você. Você tem algumas abordagens,
# uma é realizar um novo split no treino. Outra é fazer uso de classificadores com CV no fim.
# Tipo LogisticRegressionCV (ver na API). Por fim, você pode fazer uso da classe GridSearchCV.
# Leia a documentação da mesma.
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
import numpy as np

In [50]:
#getting our dataset
df = pd.read_csv("winequality-white.csv", sep = ";")
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36           20.70      0.045   
1               6.3             0.300         0.34            1.60      0.049   
2               8.1             0.280         0.40            6.90      0.050   
3               7.2             0.230         0.32            8.50      0.058   
4               7.2             0.230         0.32            8.50      0.058   
5               8.1             0.280         0.40            6.90      0.050   
6               6.2             0.320         0.16            7.00      0.045   
7               7.0             0.270         0.36           20.70      0.045   
8               6.3             0.300         0.34            1.60      0.049   
9               8.1             0.220         0.43            1.50      0.044   
10              8.1             0.270         0.41            1.45      0.033   
11              8.6             0.230         0.40            4.20      0.035   
12              7.9             0.180         0.37            1.20      0.040   
13              6.6             0.160         0.40            1.50      0.044   
14              8.3             0.420         0.62           19.25      0.040   
15              6.6             0.170         0.38            1.50      0.032   
16              6.3             0.480         0.04            1.10      0.046   
17              6.2             0.660         0.48            1.20      0.029   
18              7.4             0.340         0.42            1.10      0.033   
19              6.5             0.310         0.14            7.50      0.044   
20              6.2             0.660         0.48            1.20      0.029   
21              6.4             0.310         0.38            2.90      0.038   
22              6.8             0.260         0.42            1.70      0.049   
23              7.6             0.670         0.14            1.50      0.074   
24              6.6             0.270         0.41            1.30      0.052   
25              7.0             0.250         0.32            9.00      0.046   
26              6.9             0.240         0.35            1.00      0.052   
27              7.0             0.280         0.39            8.70      0.051   
28              7.4             0.270         0.48            1.10      0.047   
29              7.2             0.320         0.36            2.00      0.033   
...             ...               ...          ...             ...        ...   
4868            5.8             0.230         0.31            4.50      0.046   
4869            6.6             0.240         0.33           10.10      0.032   
4870            6.1             0.320         0.28            6.60      0.021   
4871            5.0             0.200         0.40            1.90      0.015   
4872            6.0             0.420         0.41           12.40      0.032   
4873            5.7             0.210         0.32            1.60      0.030   
4874            5.6             0.200         0.36            2.50      0.048   
4875            7.4             0.220         0.26            1.20      0.035   
4876            6.2             0.380         0.42            2.50      0.038   
4877            5.9             0.540         0.00            0.80      0.032   
4878            6.2             0.530         0.02            0.90      0.035   
4879            6.6             0.340         0.40            8.10      0.046   
4880            6.6             0.340         0.40            8.10      0.046   
4881            5.0             0.235         0.27           11.75      0.030   
4882            5.5             0.320         0.13            1.30      0.037   
4883            4.9             0.470         0.17            1.90      0.035   
4884            6.5             0.330         0.38            8.30      0.048   
4885            6.6             0.340

In [7]:
#we took 20% of the data for test and 80% for the training
y = df['quality']
x_train,x_test,y_train,y_test = train_test_split(df,y,test_size=0.2)

In [10]:
x_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
3292            6.6             0.280         0.41            7.00      0.046   
3541            8.1             0.260         0.27            4.30      0.030   
3483            6.1             0.360         0.26            8.15      0.035   
2395            7.0             0.270         0.29            3.90      0.059   
4436            6.7             0.280         0.28            4.50      0.051   
1529            6.6             0.210         0.49           18.15      0.042   
2557            6.4             0.150         0.44            1.20      0.043   
1101            6.3             0.170         0.42            2.80      0.028   
3578            6.7             0.220         0.22            1.20      0.038   
447             6.5             0.410         0.24           14.00      0.048   
2091            7.2             0.240         0.19            7.70      0.045   
2937            7.7             0.250         0.30            7.80      0.038   
4525            5.8             0.130         0.22           12.70      0.058   
2692            6.9             0.310         0.32            1.20      0.024   
3596            6.6             0.170         0.28            1.10      0.034   
4112            6.0             0.200         0.25            2.00      0.041   
2838            6.9             0.150         0.29            2.30      0.033   
4775            5.0             0.270         0.40            1.20      0.076   
4165            6.6             0.220         0.35            1.40      0.050   
1144            7.2             0.250         0.32            1.50      0.047   
3709            6.7             0.310         0.09            1.40      0.039   
3205            6.8             0.450         0.36            5.00      0.033   
2740            6.3             0.200         0.19           12.30      0.048   
614             7.5             0.210         0.68           10.90      0.045   
3458            5.8             0.320         0.20            2.60      0.027   
1852            6.4             0.180         0.31            1.60      0.049   
3939            6.2             0.270         0.32            6.30      0.048   
2944            7.1             0.290         0.34            7.80      0.036   
2730            6.8             0.300         0.22            6.20      0.060   
3107            7.7             0.250         0.49            2.50      0.047   
...             ...               ...          ...             ...        ...   
2271            6.7             0.250         0.26           13.50      0.060   
760             6.9             0.180         0.38            8.10      0.049   
2721            8.2             0.370         0.64           13.90      0.043   
2309            8.1             0.280         0.34            1.30      0.035   
4568            6.4             0.300         0.27            4.40      0.055   
3535            6.4             0.280         0.44            7.10      0.048   
4897            6.0             0.210         0.38            0.80      0.020   
2262            8.5             0.250         0.31            2.80      0.032   
650             7.1             0.260         0.34           14.40      0.067   
746             7.0             0.210         0.34            8.50      0.033   
932             6.5             0.260         0.28           12.50      0.046   
4856            7.1             0.230         0.39           13.70      0.058   
2668            9.6             0.655         0.21            2.00      0.039   
3014            7.0             0.450         0.34           19.80      0.040   
1477            7.6             0.510         0.24            1.20      0.040   
438             7.4             0.155         0.34            2.30      0.045   
3927            6.5             0.220         0.31            3.90      0.046   
4861            5.5             0.310

In [16]:
#perfoming logistics regression on our data 
lr = LogisticRegression()
lr.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
#we now look at getting the coefficient and intercept of our model

In [18]:
print(lr.coef_)
print(lr.intercept_)

[[ 4.56920200e-01 -7.61551875e-02  9.69004970e-02  5.65274561e-02
   5.48365631e-02  1.80642655e-02  2.19035643e-03  2.65053634e-01
   9.76800191e-01 -1.94847817e-02  5.29414480e-01 -4.22978967e+00]
 [ 2.89933454e-01  1.47142544e+00 -5.51601288e-01 -2.44879259e-02
   8.17110383e-02 -3.69208519e-02  4.06220931e-03  1.40656221e+00
   2.68527557e+00  4.55319875e-01  3.64164270e-01 -4.14047080e+00]
 [ 1.60270910e-01 -3.92164933e-01  4.72291234e-01  1.53621199e-02
   9.34518206e-01  3.52927345e-03  4.64376260e-03  5.31460586e+00
   1.81809687e+00 -3.37195863e-01 -2.68587262e-01 -2.96680385e+00]
 [-5.62174946e-02 -2.79126652e+00  4.81487186e-01  1.50107438e-02
  -2.54591988e-01  2.48397163e-04  1.72000269e-04 -2.38047303e-01
  -3.29162661e-01  1.53233139e-01  9.22492325e-02  2.01369088e-01]
 [-3.40031953e-01 -1.05632489e+00 -8.05105653e-01 -4.38871078e-02
  -7.93518038e-01 -7.91303116e-03 -1.62181652e-03 -3.92118211e+00
  -2.13259004e+00  6.12349019e-01 -1.90136378e-02  2.63841618e+00]
 [-1.

In [29]:
#checking how our model is performing
lr_pred = lr.predict(x_test)

In [27]:
#to perform validation using knn, we take our k value to be 3
classifier = KNeighborsClassifier(n_neighbors=3,metric='euclidean')
classifier.fit(x_train, y_train)

In [28]:
#checking how our model performs 
k_pred = classifier.predict(x_test) 

In [44]:
#getting our precisions 
knn_precision = precision_recall_fscore_support(y_test, k_pred, average='weighted')
lr_precision = precision_recall_fscore_support(y_test, lr_pred, average='weighted')


In [45]:
print("Quality of knn model")
print("Precision:", knn_precision[0])
print("Recall:", knn_precision[1])
print("F1:", knn_precision[2], '\n')


print("Quality of regression model")
print("Precision:", lr_precision[0])
print("Recall:", lr_precision[1])
print("F1:", lr_precision[2])

Quality of knn model
Precision: 0.5167860933784639
Recall: 0.5163265306122449
F1: 0.5083742995748806 

Quality of regression model
Precision: 0.8201876830271143
Recall: 0.8683673469387755
F1: 0.8338154711273461


In [46]:
#now we get our confusion matrix
lr_conf_mat = confusion_matrix(y_test, lr_pred)
knn_conf_mat = confusion_matrix(y_test, k_pred)

In [47]:
#printing the confusion matrix
print("confusion matrix of logistic regression")
print(lr_conf_mat)

confusion matrix of logistic regression
[[  0   0   3   0   0   0   0]
 [  0   0  33   0   0   0   0]
 [  0   0 282   3   0   0   0]
 [  0   0   0 435   0   0   0]
 [  0   0   0  55 133   0   0]
 [  0   0   0   0  34   1   0]
 [  0   0   0   0   0   1   0]]


In [48]:
#printing the confusion matrix
print("confusion matrix of knn")
print(knn_conf_mat)

confusion matrix of knn
[[  1   0   1   1   0   0   0]
 [  3   5  13  12   0   0   0]
 [  1  23 133 118  10   0   0]
 [  1   7 108 284  33   2   0]
 [  0   1  21  84  79   3   0]
 [  0   0   1  17  13   4   0]
 [  0   0   0   1   0   0   0]]


In [49]:
# YOUR CODE HERE
#raise NotImplementedError()

Explique e discuta sobre os resultados encontrados no campo abaixo.

YOUR ANSWER HERE

from the above results, we can see that the quality of the logistic model is better than the knn model since with knn, choosing the best value of k can be very tricky. so overall, the logistic model performs better than the regression model